loadstring(game:HttpGet("https://raw.githubusercontent.com/Fujiokada/Random/refs/heads/main/roll"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Fujiokada/Random/refs/heads/main/idk2"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Fujiokada/Random/refs/heads/main/brew1"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Fujiokada/Random/refs/heads/main/buy"))()
print("Successfully loaded")
